theme: jekyll-theme-midnight
# deployment
host: 0.0.0.0
port: 8080
baseurl: ""
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "admin/**"
    values:
      sitemap:         false
