theme: jekyll-theme-architect
# deployment
host: 0.0.0.0
port: 8080
repository: "salesucation/salesucation.github.io"
plugins:
  - jekyll-sitemap
defaults:
  -
    scope:
      path:            "admin/**"
    values:
      sitemap:         false